language: generic
sudo: required

services: 
    - docker
before_install:
    - docker build -t mainak/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mainak/docker-react npm run test -- --coverage